// app/api/pdf/route.js
// PDF generation for audit reports using Puppeteer
// Generates professional PDF reports from audit data

import { NextResponse } from 'next/server';
import puppeteer from 'puppeteer';

export async function POST(req) {
  let browser = null;
  
  try {
    const { auditData, leadData, shareId } = await req.json();
    
    if (!auditData || !leadData) {
      return NextResponse.json({ error: 'Missing audit or lead data' }, { status: 400 });
    }

    // Launch Puppeteer browser
    browser = await puppeteer.launch({
      headless: true,
      args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-gpu'],
    });
    
    const page = await browser.newPage();
    
    // Set viewport for consistent rendering
    await page.setViewport({ width: 1200, height: 800 });
    
    // Generate HTML content for PDF
    const htmlContent = generateReportHTML(auditData, leadData, shareId);
    
    // Set content and wait for any dynamic content to load
    await page.setContent(htmlContent, { waitUntil: 'networkidle0' });
    
    // Generate PDF with professional formatting
    const pdfBuffer = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: {
        top: '20mm',
        right: '15mm',
        bottom: '20mm',
        left: '15mm',
      },
      displayHeaderFooter: true,
      headerTemplate: `
        <div style="font-size: 10px; color: #666; width: 100%; text-align: center; margin: 0 15mm;">
          <span style="margin-left: 15mm;">AI Search Competitive Assessment</span>
        </div>
      `,
      footerTemplate: `
        <div style="font-size: 10px; color: #666; width: 100%; text-align: center; margin: 0 15mm;">
          <span style="margin-left: 15mm;">
            Generated by Abstrakt Marketing Group | Page <span class="pageNumber"></span> of <span class="totalPages"></span>
          </span>
        </div>
      `,
    });

    await browser.close();

    // Return PDF with appropriate headers
    return new NextResponse(pdfBuffer, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="ai-audit-${leadData.company?.replace(/[^a-zA-Z0-9]/g, '-')}-${new Date().toISOString().split('T')[0]}.pdf"`,
        'Content-Length': pdfBuffer.length.toString(),
      },
    });

  } catch (error) {
    console.error('[pdf] Generation error:', error);
    
    if (browser) {
      await browser.close().catch(console.error);
    }
    
    return NextResponse.json(
      { error: 'PDF generation failed', details: error.message },
      { status: 500 }
    );
  }
}

// ─── HTML Template for PDF Report ─────────────────────────────────────────────
function generateReportHTML(auditData, leadData, shareId) {
  const claude = auditData?.claude || {};
  const pageSpeed = auditData?.pageSpeed || {};
  const places = auditData?.places || {};
  const semrush = auditData?.semrush || {};
  
  const score = claude.aiVisibilityScore || 0;
  const urgency = claude.urgencyLevel || 'medium';
  const company = leadData.company || 'Your Business';
  const website = leadData.website || '';
  
  const scoreColor = score >= 70 ? '#22c55e' : score >= 40 ? '#f59e0b' : '#ef4444';
  const urgencyColor = urgency === 'high' ? '#ef4444' : urgency === 'medium' ? '#f59e0b' : '#22c55e';

  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AI Search Audit Report - ${company}</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      line-height: 1.6;
      color: #333;
      background: white;
    }
    
    .header {
      text-align: center;
      margin-bottom: 40px;
      padding: 30px 0;
      border-bottom: 3px solid #e85d04;
    }
    
    .logo-text {
      font-size: 28px;
      font-weight: bold;
      color: #333;
      margin-bottom: 5px;
    }
    
    .subtitle {
      color: #666;
      font-size: 14px;
    }
    
    .company-info {
      background: #f8f9fa;
      padding: 20px;
      border-radius: 8px;
      margin-bottom: 30px;
    }
    
    .score-section {
      text-align: center;
      margin: 30px 0;
      padding: 30px;
      background: #f8f9fa;
      border-radius: 8px;
    }
    
    .score-circle {
      width: 120px;
      height: 120px;
      border-radius: 50%;
      border: 8px solid ${scoreColor};
      display: inline-flex;
      align-items: center;
      justify-content: center;
      font-size: 36px;
      font-weight: bold;
      color: ${scoreColor};
      margin-bottom: 15px;
    }
    
    .score-label {
      font-size: 18px;
      color: #666;
      margin-bottom: 10px;
    }
    
    .urgency-badge {
      display: inline-block;
      padding: 8px 16px;
      border-radius: 20px;
      font-size: 12px;
      font-weight: bold;
      color: white;
      background: ${urgencyColor};
      text-transform: uppercase;
      letter-spacing: 1px;
    }
    
    .section {
      margin: 30px 0;
      page-break-inside: avoid;
    }
    
    .section-title {
      font-size: 20px;
      font-weight: bold;
      color: #e85d04;
      margin-bottom: 15px;
      padding-bottom: 8px;
      border-bottom: 2px solid #e85d04;
    }
    
    .metric-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 20px;
      margin: 20px 0;
    }
    
    .metric-card {
      background: #f8f9fa;
      padding: 20px;
      border-radius: 8px;
      text-align: center;
    }
    
    .metric-value {
      font-size: 24px;
      font-weight: bold;
      color: #333;
    }
    
    .metric-label {
      font-size: 12px;
      color: #666;
      text-transform: uppercase;
      letter-spacing: 1px;
      margin-top: 5px;
    }
    
    .recommendations {
      background: #fff3cd;
      border-left: 4px solid #e85d04;
      padding: 20px;
      margin: 20px 0;
    }
    
    .recommendations ol {
      margin-left: 20px;
    }
    
    .recommendations li {
      margin: 10px 0;
      line-height: 1.5;
    }
    
    .competitor-table {
      width: 100%;
      border-collapse: collapse;
      margin: 20px 0;
      font-size: 12px;
    }
    
    .competitor-table th,
    .competitor-table td {
      padding: 10px;
      text-align: left;
      border-bottom: 1px solid #ddd;
    }
    
    .competitor-table th {
      background: #f8f9fa;
      font-weight: bold;
      color: #333;
    }
    
    .summary-text {
      background: #e3f2fd;
      padding: 20px;
      border-radius: 8px;
      border-left: 4px solid #2196f3;
      margin: 20px 0;
      font-style: italic;
    }
    
    .page-break {
      page-break-before: always;
    }
    
    .footer-note {
      margin-top: 40px;
      padding: 20px;
      background: #f8f9fa;
      border-radius: 8px;
      text-align: center;
      font-size: 12px;
      color: #666;
    }
    
    @media print {
      .page-break {
        page-break-before: always;
      }
    }
  </style>
</head>
<body>
  <!-- Header -->
  <div class="header">
    <div class="logo-text">ABSTRAKT MARKETING GROUP</div>
    <div class="subtitle">AI Search Competitive Assessment</div>
  </div>

  <!-- Company Information -->
  <div class="company-info">
    <h2 style="margin-bottom: 15px; color: #333;">${company}</h2>
    <p><strong>Website:</strong> ${website}</p>
    <p><strong>Industry:</strong> ${leadData.industry || 'Not specified'}</p>
    <p><strong>Assessment Date:</strong> ${new Date().toLocaleDateString()}</p>
    <p><strong>Report ID:</strong> ${shareId || 'N/A'}</p>
  </div>

  <!-- AI Visibility Score -->
  <div class="score-section">
    <div class="score-circle">${score}</div>
    <div class="score-label">AI Visibility Score</div>
    <div class="urgency-badge">${urgency} Priority</div>
  </div>

  <!-- Executive Summary -->
  ${claude.visibilitySummary ? `
    <div class="section">
      <h2 class="section-title">Executive Summary</h2>
      <div class="summary-text">
        ${claude.visibilitySummary}
      </div>
    </div>
  ` : ''}

  <!-- Performance Metrics -->
  <div class="section">
    <h2 class="section-title">Performance Breakdown</h2>
    <div class="metric-grid">
      <div class="metric-card">
        <div class="metric-value">${claude.scoreBreakdown?.contentAuthority || '—'}</div>
        <div class="metric-label">Content Authority</div>
      </div>
      <div class="metric-card">
        <div class="metric-value">${claude.scoreBreakdown?.structuredData || '—'}</div>
        <div class="metric-label">Structured Data</div>
      </div>
      <div class="metric-card">
        <div class="metric-value">${claude.scoreBreakdown?.brandSignals || '—'}</div>
        <div class="metric-label">Brand Signals</div>
      </div>
      <div class="metric-card">
        <div class="metric-value">${claude.scoreBreakdown?.localPresence || '—'}</div>
        <div class="metric-label">Local Presence</div>
      </div>
      <div class="metric-card">
        <div class="metric-value">${pageSpeed.score || '—'}</div>
        <div class="metric-label">PageSpeed Score</div>
      </div>
      <div class="metric-card">
        <div class="metric-value">${places.found ? (places.rating || 'N/A') : 'Not Found'}</div>
        <div class="metric-label">Google Business Profile</div>
      </div>
    </div>
  </div>

  <!-- Competitor Analysis -->
  ${semrush?.competitors?.length > 0 ? `
    <div class="section page-break">
      <h2 class="section-title">Competitive Landscape</h2>
      <table class="competitor-table">
        <thead>
          <tr>
            <th>Domain</th>
            <th>Authority Score</th>
            <th>Monthly Traffic</th>
            <th>Keywords</th>
          </tr>
        </thead>
        <tbody>
          ${semrush.clientStats ? `
            <tr style="background: #fff3cd;">
              <td><strong>${company}</strong></td>
              <td>${semrush.clientStats.authorityScore}</td>
              <td>${semrush.clientStats.organicTraffic?.toLocaleString() || '—'}</td>
              <td>${semrush.clientStats.organicKeywords?.toLocaleString() || '—'}</td>
            </tr>
          ` : ''}
          ${semrush.competitors.map(comp => comp.data?.stats ? `
            <tr>
              <td>${comp.domain}</td>
              <td>${comp.data.stats.authorityScore}</td>
              <td>${comp.data.stats.organicTraffic?.toLocaleString() || '—'}</td>
              <td>${comp.data.stats.organicKeywords?.toLocaleString() || '—'}</td>
            </tr>
          ` : '').join('')}
        </tbody>
      </table>
    </div>
  ` : ''}

  <!-- Brand Gap Analysis -->
  ${claude.brandGapAnalysis ? `
    <div class="section page-break">
      <h2 class="section-title">Strategic Analysis</h2>
      <div style="line-height: 1.8; text-align: justify;">
        ${claude.brandGapAnalysis.split('\n').map(paragraph => 
          paragraph.trim() ? `<p style="margin-bottom: 15px;">${paragraph}</p>` : ''
        ).join('')}
      </div>
    </div>
  ` : ''}

  <!-- Recommendations -->
  ${claude.topRecommendations?.length > 0 ? `
    <div class="section page-break">
      <h2 class="section-title">Priority Recommendations</h2>
      <div class="recommendations">
        <ol>
          ${claude.topRecommendations.map(rec => `<li>${rec}</li>`).join('')}
        </ol>
      </div>
    </div>
  ` : ''}

  <!-- Footer -->
  <div class="footer-note">
    <p><strong>Abstrakt Marketing Group</strong></p>
    <p>This assessment was generated using proprietary AI analysis tools and industry-leading SEO data sources.</p>
    <p>For questions about this report, please contact your Abstrakt team representative.</p>
    <p style="margin-top: 10px; font-size: 10px; color: #999;">
      Generated on ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}
    </p>
  </div>
</body>
</html>
  `;
}
